### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by rbaprado** [niftylettuce/node-email-templates#101]
My setup is pretty simple:
```javascript
      emailTemplates(templatesLocation, function (err, template) {
        if (err) {
          // No good
          console.log(err);
          calllback(err);
        } else {
          var locals = {
            content: 'content',
            link: 'link',
            title: 'title'
          };
          template('signup_confirmation', locals, function (err, html, text) {
   (...)
```
My template is setup this way:
```
/email
   /signup_confirmation
        html.jade
        style.less
```

Both the jade and less files are OK (tested with the respective command line tools), but the problem goes away when I remove style.less.

I am getting the following error:
```
Uncaught TypeError: Cannot read property 'contents' of undefined
      at Object.Parser.parse (/home/buzz/Projetos/mobtag/node_modules/less/lib/less/parser/parser.js:108:20)
      at Object.renderLess [as .less] (/home/buzz/Projetos/mobtag/node_modules/email-templates/lib/templateManager.js:61:10)
      at Object.module.exports.render (/home/buzz/Projetos/mobtag/node_modules/email-templates/lib/templateManager.js:36:34)
      at /home/buzz/Projetos/mobtag/node_modules/email-templates/node_modules/async/lib/async.js:249:17
      at /home/buzz/Projetos/mobtag/node_modules/email-templates/node_modules/async/lib/async.js:125:13
      at Array.forEach (native)
      at _each (/home/buzz/Projetos/mobtag/node_modules/email-templates/node_modules/async/lib/async.js:46:24)
      at async.each (/home/buzz/Projetos/mobtag/node_modules/email-templates/node_modules/async/lib/async.js:124:9)
      at _asyncMap (/home/buzz/Projetos/mobtag/node_modules/email-templates/node_modules/async/lib/async.js:248:13)
      at Object.map (/home/buzz/Projetos/mobtag/node_modules/email-templates/node_modules/async/lib/async.js:219:23)
```
I am pretty lost here... :-(

Update: CSS works normally, LESS give me problems

**Comment by jeduan** [comment]
related: #106
