### ISSUE TITLE
Weird Require Issue

### ISSUE THREAD

**Issue by episodeyang** [niftylettuce/node-email-templates#141]
```bash
var et = require('email-templates')
Error: Cannot find module './lib/main'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

```

I installed via 
```bash
npm install --save email-templates 
```

Thanks for any help in advance!

**Comment by episodeyang** [comment]
Solved by doing 
```
npm install --save email-templates@2
```
What is the difference?

Thanks!
