### ISSUE TITLE
Support for jade -> pug name change ?

### ISSUE THREAD

**Issue by jamesbrucepower** [niftylettuce/node-email-templates#166]
Will you be updating to support the jade -> pug name change?

**Comment by InsidersByte** [comment]
+1

**Comment by nfantone** [comment]
I think this should be resolved when https://github.com/tj/consolidate.js/pull/232 is merged and `node-email-templates` updates its `consolidate` version.

**Comment by doowb** [comment]
`pub` is now in `consolidate@0.14.1`

**Comment by nfantone** [comment]
All right!  `node-email-templates` declares `"consolidate": "^0.14.0"`, so support should already be available.

**Comment by niftylettuce** [comment]
Correct it should be OK to use, if not, please let me know and I'll re-open.

**Comment by strarsis** [comment]
It doesn't work for me, node v5.3.0, pug 2.0.0-beta6, consolidate (pug dependency) 0.14.1.
````
Unhandled rejection Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /home/build/application/node_modules/consolidate/lib/consolidate.js:324:34
    at /home/build/application/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/home/build/application/node_modules/bluebird/js/release/debuggability.js:284:9)
    at Promise._resolveFromExecutor (/home/build/application/node_modules/bluebird/js/release/promise.js:480:18)
    at new Promise (/home/build/application/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/home/build/application/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.jade.render (/home/build/application/node_modules/consolidate/lib/consolidate.js:320:10)
    at /home/build/application/node_modules/email-templates/lib/template-manager.js:61:44
    at Promise._execute (/home/build/application/node_modules/bluebird/js/release/debuggability.js:284:9)
    at Promise._resolveFromExecutor (/home/build/application/node_modules/bluebird/js/release/promise.js:480:18)
    at new Promise (/home/build/application/node_modules/bluebird/js/release/promise.js:77:14)
    at render (/home/build/application/node_modules/email-templates/lib/template-manager.js:50:10)
    at renderFile (/home/build/application/node_modules/email-templates/lib/util.js:110:38)
    at /home/build/application/node_modules/email-templates/lib/email-template.js:169:61
    at tryCatcher (/home/build/application/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/build/application/node_modules/bluebird/js/release/promise.js:509:31)
    at Promise._settlePromise (/home/build/application/node_modules/bluebird/js/release/promise.js:566:18)
    at Promise._settlePromise0 (/home/build/application/node_modules/bluebird/js/release/promise.js:611:10)
    at Promise._settlePromises (/home/build/application/node_modules/bluebird/js/release/promise.js:690:18)
    at Promise._fulfill (/home/build/application/node_modules/bluebird/js/release/promise.js:635:18)
    at Promise._resolveCallback (/home/build/application/node_modules/bluebird/js/release/promise.js:430:57)
    at Promise._settlePromiseFromHandler (/home/build/application/node_modules/bluebird/js/release/promise.js:521:17)
    at Promise._settlePromise (/home/build/application/node_modules/bluebird/js/release/promise.js:566:18)
    at Promise._settlePromise0 (/home/build/application/node_modules/bluebird/js/release/promise.js:611:10)
    at Promise._settlePromises (/home/build/application/node_modules/bluebird/js/release/promise.js:690:18)
    at Promise._fulfill (/home/build/application/node_modules/bluebird/js/release/promise.js:635:18)
````
